# Generated by Django 2.2 on 2020-03-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(auto_created=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
