# Generated by Django 2.2 on 2020-03-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_usermanage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanage',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
