# Generated by Django 2.2 on 2020-03-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20200331_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManage',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='passwd',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(blank=True, choices=[('0', '男'), ('1', '女')], default=0, help_text='性别'),
        ),
    ]
