# Generated by Django 2.2 on 2020-04-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20200331_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, '男'), (1, '女')], default=0, help_text='性别'),
        ),
    ]
